version: 0.0
os: linux
files:
  - source: build_artifacts/
    destination: /data5/JCB_MobileAPI_Artifact/
    owner: jcbuser1
    group: jcbuser1
 
hooks:
  BeforeInstall:
- location: Scripts/before_install.sh
      timeout: 300
      runas: jcbuser1
 
  ApplicationStop:
- location: Scripts/stop_server.sh
      timeout: 300
      runas: jcbuser1
 
  ApplicationStart:
- location: Scripts/start_server.sh
      timeout: 300
      runas: jcbuser1
 
  ValidateService:
- location: Scripts/validate_server.sh
      timeout: 300
      runas: jcbuser1
 
