version: 0.2
 
phases:
  install:
    commands:
      - echo "Installing Maven and JDK"
      - yum update -y
      - yum install -y maven java-17-amazon-corretto.x86_64
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64
  pre_build:
    commands:
      - echo "Setting environment variables for the database"
      - export springDatasourceUrl='jdbc:mysql://10.210.196.240:3306/microservices_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true'
      - export springDatasourceUserName='root'
      - export springDatasourcePas='root@123#'
      - echo "Starting pre-build stage"
  build:
    commands:
      - echo "Running Maven clean and package"
      - echo $JAVA_HOME  # Verify JAVA_HOME is set
      - echo $PATH      # Verify PATH is updated
      - export MAVEN_OPTS="-Xmx3072m" 
      - mvn clean package -Dmaven.test.failure.ignore=true
      - echo "Listing all files after build"
      - ls -R
      - echo "Copying JAR files to the artifact directory"
      - mkdir -p build_artifacts
      - find ./JCB-Common-API-Customer -name "*.jar" -exec cp {} build_artifacts/ \;
artifacts:
  files:
    - build_artifacts/**/*.jar
  discard-paths: yes
