package com.wipro.jcb.livelink.app.auth.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.wipro.jcb.livelink.app.auth.exception.PasswordUpdateException;
import com.wipro.jcb.livelink.app.auth.repo.ContactRepo;
import com.wipro.jcb.livelink.app.auth.service.ResetPasswordService;

@RestController
@RequestMapping("/auth/web")
public class ResetPasswordController {

    private static final Logger log = LoggerFactory.getLogger(ResetPasswordController.class);

    @Autowired
    private ResetPasswordService passwordService;
    
    @Autowired
    private ContactRepo contactRepo;

    @PostMapping("/resetPassword")
    public String processResetPassword(@RequestBody String userName) {
        try {
        	String isUserNameExists = contactRepo.checkIfUserNameExists(userName);
        	if (isUserNameExists!=null) {
        		String autoGeneratedPassword = passwordService.generatePassword();
                log.info("password is before sending to DB:{}", autoGeneratedPassword);
                passwordService.updateResetPassword(autoGeneratedPassword, userName);
                //smsService.sendPassword(autoGeneratedPassword, mobileNumber);
                return "Password Reset have been done Successfully for UserID:-" + userName;
        	} else {
        		 return "Please Provide Valid Login Credentials.";
        	}
        } catch (PasswordUpdateException e) {
            log.error("Error resetting password: {}", e.getMessage(), e);
            return "Failed to update password. Please check the username and try again.";
        } catch (Exception e) {
            log.error("Error resetting password: {}", e.getMessage(), e);
            return "An unexpected error occurred. Please try again later.";
        }
    }

}
