package com.wipro.jcb.livelink.app.mob.auth.dto;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class LoginResponse {
    @ApiModelProperty(value = "Unique Accesstoken for user ", example = "alkhflajkhkcfla", required = true)
    private String accessToken;
    @ApiModelProperty(value = "Unique Token for user ", example = "alkhflajkhkcfla", required = true)
    private String token;
    @ApiModelProperty(value = "First name of user", example = "Leroy", required = false)
    private String firstName;
    @ApiModelProperty(value = "Last name of user", example = "Holland", required = false)
    private String lastName;
    @ApiModelProperty(value = "Email of user", example = "Leroy@mymail.com", required = false)
    private String email;
    @ApiModelProperty(value = "contact of user", example = "9807867676", required = false)
    private String number;
    @ApiModelProperty(value = "Image of user", example = "URL for Leroy.png", required = false)
    private String image;
    @ApiModelProperty(value = "Thumbnail image of user", example = "URL for Leroy.png", required = false)
    private String thumbnail;
    @ApiModelProperty(value = "User nationality", example = "India", required = false)
    private String country;
    @ApiModelProperty(value = "Language decided by user", example = "English", required = false)
    private String smsLanguage;
    @ApiModelProperty(value = "current timezone ", example = "GMT+5:50", required = false)
    private String timeZone;
    @ApiModelProperty(value = "Is current password generated by system", example = "true", required = false)
    private Boolean sysGenPassword;
    @ApiModelProperty(value = "roleName", example = "Customer", required = false)
    private String roleName;
    @ApiModelProperty(value = "key of user with read access", example = "chsaka", required = false)
    private String bucketAccesskey;
    @ApiModelProperty(value = "secret key of user with read access", example = "chsaka", required = false)
    private String bucketSecretkey;
    @ApiModelProperty(value = "Is current password generated by system", example = "true", required = false)
    private Boolean isSecretQuestion;
    @ApiModelProperty(value = "User Language", example = "English", required = false)
    private String language;
    private String error;
    
    public LoginResponse() {}
    
	public LoginResponse(String error) {
		this.error = "Authentication failed. Invalid username, password, or role.";
	}

	public LoginResponse(String accessToken, String token, String firstName, String lastName, String email,
			String number, String image, String thumbnail, String country, String smsLanguage, String timeZone,
			Boolean sysGenPassword, String roleName, String bucketAccesskey, String bucketSecretkey,
			Boolean isSecretQuestion, String language) {
		super();
		this.accessToken = accessToken;
		this.token = token;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.number = number;
		this.image = image;
		this.thumbnail = thumbnail;
		this.country = country;
		this.smsLanguage = smsLanguage;
		this.timeZone = timeZone;
		this.sysGenPassword = sysGenPassword;
		this.roleName = roleName;
		this.bucketAccesskey = bucketAccesskey;
		this.bucketSecretkey = bucketSecretkey;
		this.isSecretQuestion = isSecretQuestion;
		this.language = language;
	}

}
